### PR TITLE
Add rewrite draft

### PR DESCRIPTION
**Pull request by ilikesymmetry**
NOT DONE. Sharing early out of request from ZeroDev.

### CODE REVIEW

**Comment by danfinlay** [comment]
I think this is overall a huge improvement to the ERC, and is significantly closer to the structure [I originally advocated for](https://www.notion.so/metamask-consensys/Onchain-Permissions-Standard-1ca8cf7534f245cc9c06e13abbd716c7). I think this is a good point to build from.

Changes I'd be happy to see:

Re-add optional `required:boolean` parameter to the `PermissionRequest` type. (default to true)

Add optional `justification:string` to the PermissionRequest type.

A somewhat newer trend in permissions requests is to allow the requestor to provide a justification for permissions requested. There is a natural security concern with allowing an untrusted party to provide input to be presented to the user within a trusted interface, but given that it is represented in an adequate security frame, I believe it can streamline an experience that is already inalienable from a site: The ability to provide context around its own permission requests. You can witness the inalienability of this right in a variety of applications today, in which they present a fake in-app permissions prompt before initiating the system prompt, so that they can present the justification in their own terms, before handing over to what is otherwise an application-hostile permissions prompt.

It's interesting to me that the PermissionResponse doesn't include any machine-readable representation of the approved permission. We could probably still include a copy of the `PermissionRequest` object, with any changes to the policies that can be represented in a standard-compliant way.

**Comment by danfinlay** [comment]
Oh, and as I've suggested on tg: I'd also be in favor of removing `expiry` as a property in the request, and instead defining it as a policy, and recommending/mandating it for the response.

**Comment by lukaisailovic** [comment]
@danfinlay Dapp providing justification doesn't really make sense to me. It can write whatever it wants, which is a security concern as you pointed out. 
Wallet will not display it, instead it will reason about the permissions in its own way.
If wallet provides it and you have it in the response, dapp can again display whatever it wants.

This should be strictly wallet side.

**Comment by danfinlay** [comment]
> providing justification doesn't really make sense to me. It can write whatever it wants, which is a security concern as you pointed out.

It's a security concern if implemented without the consideration I noted (did you see that part?). Also, a wallet could simply ignore that field if it wanted to.

**Comment by derekchiang** [comment]
Leaving my comment from TG here for better visibility:

> while i chew on this, i do want to make a quick comment that wallet_revokePermissions as currently proposed isn't great because it looks like anyone can revoke the permission based on the context alone.  in a typical session key implementation, the permissions request will contain the public key of the signer, and the permissions response contains a context that can be safely exposed publicly.  it can be exposed publicly because later when the client uses the context, it would sign the transaction with its own private key (of the permissions signer).  this is true in both the 7679 and the 7710 flow

> so my point is that up until this point, the context can be safely exposed.  not that we recommend exposing it, of course, but it's true that it can be exposed with no security risks.  but by introducing a wallet_revokePermissions API that can revoke a permission based on the context alone, that assumption changes and now the client must secure the context, which is a big burden

So basically, we should remove `wallet_revokePermissions` in its current form.  In general I think revoking permissions should be a concern of the wallet, not of the dapp.

Regarding the other points raised in this thread:

- I also support making `expiry` a policy -- seems more elegant that way, to have one less special flags.
- Agreed that the `required` flag shouldn't have been removed.  DApps need a way to declare the permissions they need in order to function correctly.
- No particular opinion on justifications.

**Pull request closed without merging**
